# Generated by Django 3.1.5 on 2021-03-09 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('balance', models.CharField(max_length=128)),
                ('curr_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SkipTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('addr', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=128, unique=True)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('telegram_channel_id', models.CharField(max_length=128, null=True)),
                ('mainnet', models.BooleanField(default=False)),
                ('waps_balance', models.CharField(max_length=128, null=True)),
                ('weth_balance', models.CharField(max_length=128, null=True)),
                ('eth_balance', models.CharField(max_length=128, null=True)),
                ('max_gas', models.CharField(default='500000000000', max_length=128, null=True)),
                ('socket_msg', models.CharField(max_length=255, null=True)),
                ('initial_state', models.BooleanField(default=True)),
                ('skip_tokens', models.ManyToManyField(related_name='wallets', to='WapsClient.SkipTokens')),
            ],
        ),
        migrations.CreateModel(
            name='LimitAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('qnty', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=False)),
                ('tx_hash', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell'), ('stop loss', 'stop loss'), ('take profit', 'take profit')], max_length=128)),
                ('status', models.CharField(choices=[('running', 'running'), ('stopped', 'stopped'), ('failed', 'failed'), ('pending', 'pending'), ('executed', 'executed')], max_length=128)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_assets', to='WapsClient.asset')),
            ],
        ),
        migrations.CreateModel(
            name='DonorAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('addr', models.CharField(max_length=128, unique=True)),
                ('gas_multiplier', models.FloatField()),
                ('fixed_trade', models.BooleanField()),
                ('fixed_value_trade', models.CharField(max_length=128)),
                ('percent_value_trade', models.FloatField(null=True)),
                ('trade_on_confirmed', models.BooleanField()),
                ('retry_count', models.IntegerField(null=True)),
                ('follow_min', models.CharField(max_length=128, null=True)),
                ('follow_max', models.CharField(max_length=128, null=True)),
                ('slippage', models.FloatField()),
                ('donor_slippage', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='WapsClient.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='WapsClient.wallet'),
        ),
        migrations.CreateModel(
            name='DonorAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slippage', models.FloatField(default=5)),
                ('buyed_for_addr', models.CharField(max_length=128)),
                ('qnty', models.CharField(max_length=100, null=True)),
                ('buyed_for_qnty', models.CharField(max_length=100, null=True)),
                ('donor_tx_hash', models.CharField(max_length=128)),
                ('donor_sell_tx_hash', models.CharField(max_length=128, null=True)),
                ('our_tx_hash', models.CharField(max_length=128)),
                ('our_sell_tx_hash', models.CharField(max_length=128, null=True)),
                ('approve_tx_hash', models.CharField(max_length=128, null=True)),
                ('approve_failed', models.BooleanField(default=False)),
                ('donor_confirmed', models.BooleanField(default=False)),
                ('our_confirmed', models.BooleanField(default=False)),
                ('attemts', models.IntegerField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_assets', to='WapsClient.asset')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='WapsClient.donoraddr')),
            ],
            options={
                'unique_together': {('asset', 'donor')},
            },
        ),
    ]
