# Generated by Django 3.1.5 on 2021-03-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WapsClient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorasset',
            name='slippage',
        ),
        migrations.AddField(
            model_name='limitasset',
            name='slippage',
            field=models.FloatField(default=5),
        ),
    ]
