# Generated by Django 3.1.5 on 2021-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WapsClient', '0003_auto_20210309_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='fast_gas',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='low_gas',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='medium_gas',
            field=models.FloatField(null=True),
        ),
    ]
