# Generated by Django 3.1.5 on 2021-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WapsClient', '0004_auto_20210309_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='fast_gas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='low_gas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='medium_gas',
            field=models.IntegerField(null=True),
        ),
    ]
