# Generated by Django 3.1.5 on 2021-03-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WapsClient', '0008_auto_20210309_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='decimals',
            field=models.IntegerField(null=True),
        ),
    ]
