# Generated by Django 3.1.5 on 2021-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WapsClient', '0010_asset_price_for_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorasset',
            name='approve_tx_hash',
        ),
        migrations.AddField(
            model_name='asset',
            name='approve_tx_hash',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='balance',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
