# Generated by Django 3.1.5 on 2021-03-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WapsClient', '0011_auto_20210314_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiptokens',
            name='addr',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
