# Generated by Django 3.1.5 on 2021-03-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WapsClient', '0014_limitasset_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitasset',
            name='current_retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
